version: '3.8'

services:
  db:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://db:27017/tts_app
      JWT_SECRET: 9958b01c3d5c64bde5d0ce7e910341310165b1554af70dd4b999098236ededb7
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongodata:
