services:
  - type: web
    name: tts-app-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://akashkulal866087_db_user:2oE34bd5fVErFmYM@cluster0.nm753qc.mongodb.net/tts_app
      - key: JWT_SECRET
        value: 9958b01c3d5c64bde5d0ce7e910341310165b1554af70dd4b999098236ededb7
      - key: NODE_ENV
        value: production
